name: germanTTS
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - attrs==25.2.0
      - audioread==3.0.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chex==0.1.89
      - datasets==3.3.2
      - dill==0.3.8
      - etils==1.12.0
      - filelock==3.17.0
      - flax==0.10.4
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - huggingface-hub==0.29.3
      - humanize==4.12.1
      - idna==3.10
      - importlib-resources==6.5.2
      - jax==0.5.1
      - jaxlib==0.5.1
      - joblib==1.4.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - numba==0.61.0
      - numpy==2.1.3
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.6
      - pandas==2.2.3
      - pooch==1.8.2
      - propcache==0.3.0
      - protobuf==5.29.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pygments==2.19.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - simplejson==3.20.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - tensorstore==0.1.72
      - threadpoolctl==3.5.0
      - toolz==1.0.0
      - tqdm==4.67.1
      - treescope==0.1.9
      - tzdata==2025.1
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
